name: DevSecOps End to end pipline

on:
    workflow_dispatch:

jobs:
    code_quality:
          uses: ./.github/workflows/code_quality.yml

    secrets-scan:
        uses: ./.github/workflows/secret_scan.yml
    
    dependency-scan:
        uses: ./.github/workflows/dependency_scan.yml

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml

    # Build once the security scans are complete
    build:
        needs: [code_quality, secrets-scan, dependency-scan, docker-scan]
        uses: ./.github/workflows/docker_build_push.yml
        secrets: inherit

    trivy:
        needs: [build]
        uses: ./.github/workflows/image_scan.yml
        secrets: inherit

    # Deploy to Production
    deploy:
        needs: [trivy]
        uses: ./.github/workflows/Deploy-to-server.yml
        secrets: inherit

        