#This is workflow name
name: Hello
#runs on trigger
on: 
#to be run only when asked to run.
   workflow_dispatch:
#these are jobs inside the workflows
jobs: 

  #this is the name of the job
  greet: 
    #this is github runner
     runs-on: ubuntu-latest
     steps:
      - name: say hello to users
        run: echo "Hello Dosto"
        
      - name: say hello to username
        run: echo "Hello $USER"
 
  details:
    runs-on: ubuntu-latest
    steps:
      - name: version of python, docker, etc
        run: docker --version && python --version
