# API Keys, Sensitive data, credentials
# GitLeaks
name: Secrets_Scan

on:
    workflow_call:

jobs:
    secrets-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Run GitLeaks Scanner
              uses: gitleaks/gitleaks-action@v2
              env:
                # set: FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # git hub action manages it.